# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda4ac1be337156627e8e54432d67aac832ee09a33ec0ef9a446884a9e734327c5adca315530a23988b9544ddf1c6be2b33bf78f4d5582795a9f42d17f1e21ee

test:
  secret_key_base: 8657650283600295ef712c444034e0829f3f192785582767cf1e83b74b4bc970fae5065bfeff632a19112d955f1831a3551aab1b3bf0e559f74a70d5242830b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
